# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
- task: DotNetCoreCLI@2
 
- task: Bash@3
  inputs:
    command: 'build'
    projects: |
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
- task: AzureStaticWebApp@0
  inputs:
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)' # Update this to match your needs
 

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
